CREATE DATABASE PCLINICS
GO

USE PCLINICS
GO

CREATE TABLE CLINICA (
	idClinica INT PRIMARY KEY IDENTITY(1,1),
	nomeClinica CHAR(250),
	endereco CHAR(300)
);
GO

CREATE TABLE VETERINARIO (
	idVeterinario INT PRIMARY KEY IDENTITY(1,1),
	idClinica INT FOREIGN KEY REFERENCES CLINICA(idClinica),
	nomeVeterinario CHAR(200)
);
GO

CREATE TABLE DONO (
	idDono INT PRIMARY KEY IDENTITY(1,1),
	nomeDono CHAR(200)
);
GO

CREATE TABLE TIPOPET (
	idTipoPet INT PRIMARY KEY IDENTITY(1,1),
	nomeTipoPet CHAR(100)
);
GO

CREATE TABLE RACA (
	idRaca INT PRIMARY KEY IDENTITY(1,1),
	idTipoPet INT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
	nomeRaca CHAR(50)
);
GO

CREATE TABLE PET (
	idPet INT PRIMARY KEY IDENTITY(1,1),
	idDono INT FOREIGN KEY REFERENCES DONO(idDono),
	idRaca INT FOREIGN KEY REFERENCES RACA(idRaca),
	nomePet CHAR(50),
	dataNascimento CHAR(50)
);
GO

CREATE TABLE CONSULTA (	
	idConsulta INT PRIMARY KEY IDENTITY(1,1),
	idVeterinario INT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
	idPet INT FOREIGN KEY REFERENCES PET(idPet),
	dataConsulta DATE
);
GO